server:
  port: 8081
  servlet:
    session:
      timeout: 1800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    default-encoding: UTF-8
    properties:
      timeout: 30000
      connection-timeout: 5000
      write-timeout: 10000
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

email:
  handler:
    form: ${MAIL_USERNAME}
    to: ${MAIL_USERNAME}
    name: "蜥蜴"
    subject: "默认主题"
    content: "Hello World!"
    html: false

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  configuration:
#    \u63A7\u5236\u53F0\u6253\u5370sql\u8BED\u53E5
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

apply:
  strategy:
    map:
      pwd-reset: "PwdResetStrategy"